### ISSUE TITLE
samtools execution does not work after building container

### ISSUE THREAD

**Issue by jayaramanp** [ljishen/ga4gh-testing#1]
Hello, 
when i used your image to run a samtools example, i found i got this:

root@05a1aa33a936:~/samtools-1.3.1# samtools
samtools: error while loading shared libraries: libhts.so.1: cannot open shared object file: No such file or directory

I've figured out what the problem might be, looks like the ./configure --with-htslib does not point to the right directory. 

if you change the parameter of --with-htslib to point to the src directory with the lib files, it works!

RUN ./configure --with-htslib=/root/htslib-${SAMTOOLS_VERSION} \
    && make \
    && make install

works!
Please do change your Dockerfile to fix this! I really appreciate the provision of this image for running samtools!

root@05a1aa33a936:~/samtools-1.3.1# samtools

Program: samtools (Tools for alignments in the SAM format)
Version: 1.3.1 (using htslib 1.3.1)

Usage:   samtools <command> [options]

Commands:
  -- Indexing
     dict           create a sequence dictionary file
     faidx          index/extract FASTA
     index          index alignment

  -- Editing
     calmd          recalculate MD/NM tags and '=' bases
     fixmate        fix mate information
     reheader       replace BAM header
     rmdup          remove PCR duplicates
     targetcut      cut fosmid regions (for fosmid pool only)
     addreplacerg   adds or replaces RG tags

  -- File operations
     collate        shuffle and group alignments by name
     cat            concatenate BAMs
     merge          merge sorted alignments
     mpileup        multi-way pileup
     sort           sort alignment file
     split          splits a file by read group
     quickcheck     quickly check if SAM/BAM/CRAM file appears intact
     fastq          converts a BAM to a FASTQ
     fasta          converts a BAM to a FASTA

  -- Statistics
     bedcov         read depth per BED region
     depth          compute the depth
     flagstat       simple stats
     idxstats       BAM index stats
     phase          phase heterozygotes
     stats          generate stats (former bamcheck)

  -- Viewing
     flags          explain BAM flags
     tview          text alignment viewer
     view           SAM<->BAM<->CRAM conversion
     depad          convert padded BAM to unpadded BAM

**Comment by ljishen** [comment]
Thanks for showing this problem. I have fixed it and you can now use `docker run --rm -t ljishen/samtools` to run any samtools commands just as the description in the README.
